name: Chaoticmnemonic
favicon: null
layout_spectrum: 0.3222129810601473
typography_spectrum: 0.58104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d3cf'
    - '#020204'
    - '#b6b3ac'
    - '#5e5d58'
    - '#488d8a'
  brandStrength: 0.75
  lightness: 0.47533003450371325
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
